config/routes.rb
Site::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :friends

  resources :messengers

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  
  get '/users/show_friends' => 'users#show_friends'
  match '/users/destroy_friends' => 'users#destroy_friends'
  match '/users/info/' => 'users#info'
  
  match 'items/byCollection/:id' => 'items#showbyid'
  resources :items

  resources :photos

  resources :administrations

  resources :searchadvanced

  resources :categories

  match 'collections/byUserMail/:email' => 'collections#showbymail', :constraints => { :email => /[^\/]*/ }
  match 'collections/byUser/:id' => 'collections#showbyuser'
  match 'collections/byCategory/:name' => 'collections#showbyname'
  match 'collections/searchadvanced' => 'collections#searchadvanced'

  
  get '/invite/create' => 'invite#create'
  get '/invite/show' => 'invite#show'
  get '/invite/accept' => 'invite#accept'
  get '/invite/deny' => 'invite#deny'
  resources :collections












  root :to => 'collections#index'


end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :items, :dependent => :delete_all
  belongs_to :category
  belongs_to :user

  accepts_nested_attributes_for :items
  validates :title, :presence => {:message => 'cannot be blank.'}
  validate :check_items
  
    def check_items
      if self.items.size < 1 || self.items.all?{|item| item.marked_for_destruction? }
        self.errors[:base] << "A collection must have at least one item."
      end
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # GET /collections
  # GET /collections.json
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  
  def index
    @search = Collection.search(params[:search])
    @collections = @search.all
    # @collections = Collection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/byCategory/Records
  # GET /collections/byCategory/Records.json
  def showbyname
    category = Category.where("name=?", params[:name]).first
    @collections = Collection.where("category_id=?", category.id)
    @title = params[:name]
    respond_to do |format|
      format.html # showbyname.html.erb
      format.json { 
        render :json => @collections.to_json(
          :include => {
              :user => { 
                :only => :name 
              },
              :items => {
                :only => :title,
                :methods => [:url_thumb]
              }
          },
          
          :only => [:title, :description, :created_at, :visibility, :id]
          
          )
      }
    end
  end
  
  def showbyuser
    #name = User.where("user_id=?", params[:id]).name
    @collections = Collection.where("user_id=?", params[:id])
    @id = params[:id]
    @title = params[:name]
    respond_to do |format|
      format.html # showbyuser.html.erb
      format.json {
        render :json => @collections.to_json(
          :include => {
              :user => {
                :only => :name
              },
              :items => {
                :only => :title,
                :methods => [:url_thumb]
              }
          },

          :only => [:title, :description, :created_at, :visibility, :id]

          )
      }
    end
  end

  def showbymail
    user = User.where("email=?" , params[:email]).first
    @collections = Collection.where("user_id=?", user.id)
    @title = params[:name]
    respond_to do |format|
      format.html # showbymail.html.erb
      format.json {
        render :json => @collections.to_json(
          :include => {
              :user => {
                :only => :name
              },
              :items => {
                :only => :title,
                :methods => [:url_thumb]
              }
          },

          :only => [:title, :description, :created_at, :visibility, :id]

          )
      }
    end
  end

  def show
    @collection = Collection.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end
  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new
    
    @collection.items.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    
    @collection = Collection.new(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to :controller=>"collections", :action=>"showbyuser", :id => @collection.user }
      format.json { head :ok }
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= nested_form_for(@collection, :html => { :id => "newCollection"}) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<fieldset>
	<legend>Collection details</legend>
	  <div class="field">
	    <%= f.text_field :title, :placeholder => "Title" %>
	  </div>
	  <div class="field">
	    <%= f.text_area :description, :placeholder => "Description" %>
	  </div>
	<%= collection_select(:collection, :category_id, Category.all, :id, :name) %><br/>
	<div class="field">
	  <%= f.label "Private" %>
	  <%= f.check_box :visibility %>
	</div>
</fieldset>
<fieldset>
	<legend>Items</legend>
	<%= f.fields_for :items %>
	<%= f.link_to_add "Add item", :items, :class => "clean-gray" %>	
</fieldset>
<fieldset>
	<legend>Save collection</legend>
  <div class="actions">
    <%= f.submit "Submit", :id => "commit", :class => "clean-gray" %>
  </div>
</fieldset>
<% end %>

app/views/collections/_item_fields.erb
<div class="field">
  <%= f.text_field :title, :placeholder => "Title" %>
</div>
<div class="field">
  <%= f.text_area :description, :placeholder => "Description" %>
</div>
<div class="field">
  <%= f.label :tradeable %>
  <%= f.check_box :tradeable %>
</div>
<div class="field">
  <%= f.label :sellable %>
  <%= f.check_box :sellable %>
</div>
<div class="field">
  <%= f.file_field :photo, :placeholder => "Picture" %>
</div>
<%= f.link_to_remove "Remove", :class => "clean-gray" %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1 style="text-align:center">Collections</h1>

<h1><%= @title %></h1>

<% @collections.each do |collection| %>
<div class="collectionWrapper">
	<div id="userInfo">
	    <%= image_tag collection.user.photo.url(:thumb) %>
			<h1><%= link_to collection.user.name, :controller => :users, :action => :info, :id => collection.user.id %></h1>
			<% if user_signed_in? && current_user.has_not_reached(collection.user) %>
			<%= link_to "Add as friend", :controller => :invite, :action => :create, :dest_id => collection.user.id %>
			<% end %>
	</div>

	<div id="collectionData">
		<div id="collectionTopBar">
			<%= link_to collection.title, collection %>
		</div>
		<div id="collectionDescription"><%= collection.description %></div>

		<% if collection.visibility %>
			<%= image_tag "private.png", :alt => "Private collection", :id => "collectionVis" %>
			<% else %>
			<%= image_tag "public.png", :alt => "Public collection", :id => "collectionVis" %>
			<% end %>

			<!--<%= collection.created_at %>--><br />
			<% if !collection.visibility %>

				<div id="collectionDataPhotos">
					<% collection.items[0,6].each do |item| %>
						<div id="photo">
						<a class="group" rel="photo_group[<%= collection.id %>]" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
						<%= image_tag item.photo.url(:thumb) %><br/>
						<% if user_signed_in? && current_user == item.collection.user %>
							<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
						<% end %>
						</a>
						</div>
					<% end %>
					<%= link_to "...", collection %>
				</div>
			<% else %>
				<% if user_signed_in? && (collection.user.users.include?(current_user) || collection.user == current_user) %>
					<div id="collectionDataPhotos">
						<% collection.items[0,6].each do |item| %>
							<div id="photo">
							<a class="group" rel="photo_group[<%= collection.id %>]" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
							<%= image_tag item.photo.url(:thumb) %><br/>
							<% if user_signed_in? && current_user == item.collection.user %>
								<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
							<% end %>
							</a>
							</div>
						<% end %>
						<%= link_to "...", collection %>
					</div>
				<% else %>
				This collection is private, add this user as a friend to see his private collections.
				<% end %>

			<% end %>

	</div>
</div>
<br/>
<% end %>


app/views/collections/new.html.erb
<%= render 'form' %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>  <%= @collection.title %> </h1>
</p>

<p>
  <h3>  <%= @collection.description %> </h3>
</p>

<% if !@collection.visibility %>
	<div id="collectionDataPhotos">
	<% @collection.items.each do |item| %> 
		<div id="photo">
			<a class="group" rel="photo_group" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
			<%= image_tag item.photo.url(:thumb) %><br/>
			<% if user_signed_in? && current_user == @collection.user %>
			<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
			<% end %>
			</a>
		</div>
	<% end %>
	</div>
<% else %>
	<% if user_signed_in? && (@collection.user.users.include?(current_user) || @collection.user == current_user) %>
	<div id="collectionDataPhotos">
	<% @collection.items.each do |item| %> 
		<div id="photo">
			<a class="group" rel="photo_group" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
			<%= image_tag item.photo.url(:thumb) %><br/>
			<% if user_signed_in? && current_user == @collection.user %>
			<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
			<% end %>
			</a>
		</div>
	<% end %>
	</div>
	<% else %>
	You don't have access to this collection. Add this user as a friend.<br/>
	<% end %>
<% end %><br />
<%= link_to 'Back', :back %> 
</div>

app/views/collections/showbymail.html.erb
<h1 style="text-align:center"><%= @title %></h1>

<% @collections.each do |collection| %>
<div class="collectionWrapper">
	<div id="userInfo">
	    <%= image_tag collection.user.photo.url(:thumb) %>
			<h1><%= link_to collection.user.name, :controller => :users, :action => :info, :id => collection.user.id %></h1>
			<% if user_signed_in? && current_user.has_not_reached(collection.user) %>
			<%= link_to "Add as friend", :controller => :invite, :action => :create, :dest_id => collection.user.id %>
			<% end %>
	</div>

	<div id="collectionData">
		<div id="collectionTopBar">
			<%= link_to collection.title, collection %>
		</div>
		<div id="collectionDescription"><%= collection.description %></div>
		
		<% if collection.visibility %>
			<%= image_tag "private.png", :alt => "Private collection", :id => "collectionVis" %>
			<% else %>
			<%= image_tag "public.png", :alt => "Public collection", :id => "collectionVis" %>
			<% end %>
			
			
			<!--<%= collection.created_at %>--><br /> 

			<div id="collectionDataPhotos">
				<% collection.items[0,6].each do |item| %>
					<div id="photo">
					<a class="group" rel="photo_group[<%= collection.id %>]" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
					<%= image_tag item.photo.url(:thumb) %><br/>
					</a>
					</div>
				<% end %>					
				<%= link_to "...", collection %>
			</div>
	</div>
</div>
<br/>
<% end %>

app/views/collections/showbyname.html.erb
<h1 style="text-align:center"><%= @title %></h1>

<% @collections.each do |collection| %>
<div class="collectionWrapper">
	<div id="userInfo">
	    <%= image_tag collection.user.photo.url(:thumb) %>
			<h1><%= link_to collection.user.name, :controller => :users, :action => :info, :id => collection.user.id %></h1>
			<% if user_signed_in? && current_user.has_not_reached(collection.user) %>
			<%= link_to "Add as friend", :controller => :invite, :action => :create, :dest_id => collection.user.id %>
			<% end %>
	</div>

	<div id="collectionData">
		<div id="collectionTopBar">
			<%= link_to collection.title, collection %>
			<% if user_signed_in? && current_user.id == @id.to_i %>
			<%= link_to image_tag("delete.png"), collection, confirm: 'Are you sure you want to delete collection?', method: :delete %>
			<%= link_to image_tag("edit.png"), edit_collection_path(collection) %>
			<% end %>
		</div>
		<div id="collectionDescription"><%= collection.description %></div>
		
		<% if collection.visibility %>
			<%= image_tag "private.png", :alt => "Private collection", :id => "collectionVis" %>
			<% else %>
			<%= image_tag "public.png", :alt => "Public collection", :id => "collectionVis" %>
			<% end %>
			
			
			<!--<%= collection.created_at %>--><br /> 

			<% if !collection.visibility %>
			
				<div id="collectionDataPhotos">
					<% collection.items[0,6].each do |item| %>
						<div id="photo">
						<a class="group" rel="photo_group[<%= collection.id %>]" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
						<%= image_tag item.photo.url(:thumb) %><br/>
						<% if user_signed_in? && current_user == item.collection.user %>
							<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
						<% end %>
						</a>
						</div>
					<% end %>					
					<%= link_to "...", collection %>
				</div>
			<% else %>					
				<% if user_signed_in? && (collection.user.users.include?(current_user) || collection.user == current_user) %>			
					<div id="collectionDataPhotos">
						<% collection.items[0,6].each do |item| %>
							<div id="photo">
							<a class="group" rel="photo_group[<%= collection.id %>]" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
							<%= image_tag item.photo.url(:thumb) %><br/>
							<% if user_signed_in? && current_user == item.collection.user %>
								<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
							<% end %>
							</a>
							</div>
						<% end %>					
						<%= link_to "...", collection %>
					</div>			
				<% else %>
				This collection is private, add this user as a friend to see his private collections.
				<% end %>
			
			<% end %>
	</div>
</div>
<br/>
<% end %>
	

app/views/collections/showbyuser.html.erb
<h1 style="text-align:center"><%= @title %></h1>
	<% if user_signed_in? && current_user.id == @id.to_i %>
	<button class="clean-gray" onClick="window.location.href='<%= new_collection_path %>'">Add collection</button>	
	<% end %>

	<% @collections.each do |collection| %>
	<div class="collectionWrapper">
		<div id="userInfo">
		    <%= image_tag collection.user.photo.url(:thumb) %>
				<h1><%= link_to collection.user.name, :controller => :users, :action => :info, :id => collection.user.id %></h1>
				<% if user_signed_in? && current_user.has_not_reached(collection.user) %>
				<%= link_to "Add as friend", :controller => :invite, :action => :create, :dest_id => collection.user.id %>
				<% end %>
		</div>

		<div id="collectionData">
			<div id="collectionTopBar">
				<%= link_to collection.title, collection %>
				<% if user_signed_in? && current_user.id == @id.to_i %>
				<%= link_to image_tag("delete.png"), collection, confirm: 'Are you sure you want to delete collection?', method: :delete %>
				<%= link_to image_tag("edit.png"), edit_collection_path(collection) %>
				<% end %>
			</div>
			<div id="collectionDescription"><%= collection.description %></div>
			
			<% if collection.visibility %>
				<%= image_tag "private.png", :alt => "Private collection", :id => "collectionVis" %>
				<% else %>
				<%= image_tag "public.png", :alt => "Public collection", :id => "collectionVis" %>
				<% end %>
				
				
				<!--<%= collection.created_at %>--><br /> 

				<% if !collection.visibility %>

					<div id="collectionDataPhotos">
						<% collection.items[0,6].each do |item| %>
							<div id="photo">
							<a class="group" rel="photo_group[<%= collection.id %>]" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
							<%= image_tag item.photo.url(:thumb) %><br/>
							<% if user_signed_in? && current_user == item.collection.user %>
								<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
							<% end %>
							</a>
							</div>
						<% end %>					
						<%= link_to "...", collection %>
					</div>
				<% else %>	
					<% if user_signed_in? && (collection.user.users.include?(current_user) || collection.user == current_user) %>			
						<div id="collectionDataPhotos">
							<% collection.items[0,6].each do |item| %>
								<div id="photo">
								<a class="group" rel="photo_group[<%= collection.id %>]" href="<%= item.photo.url(:original) %>" title="<h1><%= item.title %></h1><br/><%= item.description %>">
								<%= image_tag item.photo.url(:thumb) %><br/>
								<% if user_signed_in? && current_user == item.collection.user %>
									<%= link_to image_tag("delete.png", :id => "deleteItem"), item, confirm: 'Are you sure you want to delete item?', method: :delete %>
								<% end %>
								</a>
								</div>
							<% end %>					
							<%= link_to "...", collection %>
						</div>			
					<% else %>
					This collection is private, add this user as a friend to see his private collections.
					<% end %>

				<% end %>
		</div>
	</div>
	<br/>
	<% end %>