config/routes.rb
Site::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :friends

  resources :messengers

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  
  get '/users/show_friends' => 'users#show_friends'
  match '/users/destroy_friends' => 'users#destroy_friends'
  match '/users/info/' => 'users#info'
  
  match 'items/byCollection/:id' => 'items#showbyid'
  resources :items

  resources :photos

  resources :administrations

  resources :searchadvanced

  resources :categories

  match 'collections/byUserMail/:email' => 'collections#showbymail', :constraints => { :email => /[^\/]*/ }
  match 'collections/byUser/:id' => 'collections#showbyuser'
  match 'collections/byCategory/:name' => 'collections#showbyname'
  match 'collections/searchadvanced' => 'collections#searchadvanced'

  
  get '/invite/create' => 'invite#create'
  get '/invite/show' => 'invite#show'
  get '/invite/accept' => 'invite#accept'
  get '/invite/deny' => 'invite#deny'
  resources :collections












  root :to => 'collections#index'


end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController
  http_basic_authenticate_with :name => "admin@merchant.com", :password => "merchant"
end

app/views/administrations/index.html.erb
<%= link_to 'New Category', new_category_path %>

<div class="tabber">

  <div class="tabbertab" title="Items">
    <table>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Tradeable</th>
        <th>Sellable</th>
        <th>Date</th>
        <th>Collection</th>
        <th>Photo</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% Item.all.each do |item| %>
        <tr>
          <td><%= item.title %></td>
          <td><%= item.description %></td>
          <td><%= item.tradeable %></td>
          <td><%= item.sellable %></td>
          <td><%= item.date %></td>
          <td><%= item.collection_id %></td>
          <td><%= item.photo_id %></td>
          <td><%= link_to 'Show', item %></td>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="tabbertab" title="Collections">
    <table>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Visibility</th>
        <th>User</th>
        <th>Category</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% Collection.all.each do |collection| %>
        <tr>
          <td><%= collection.title %></td>
          <td><%= collection.description %></td>
          <td><%= collection.visibility %></td>
          <td><%= collection.user_id %></td>
          <td><%= collection.category_id %></td>
          <td><%= link_to 'Show', collection %></td>
          <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
          <td><%= link_to 'Destroy', collection, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="tabbertab" title="Categories">
    <table>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% Category.all.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>

</div>